name: Deploy to AWS S3

on:
  push:
    branches:
      - main
      - schema/*
    tags:
      - prod-*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Deployment Environment
        id: set-env
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/schema/* ]]; then
            echo "BUCKET_NAME=dh-global-cpi-json-schema-files" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_TEST_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_TEST_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
            echo "AWS_REGION=eu-central-1" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/tags/prod-* ]]; then
            echo "BUCKET_NAME=my-prod-bucket" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_PROD_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
            echo "AWS_REGION=eu-central-1" >> $GITHUB_ENV
          else
            echo "This branch is not set up for deployment."
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://${{ env.BUCKET_NAME }} --exclude "*" --include "schema-*"

